version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: norutin-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  app:
    image: server-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: sh -c "./gradlew flywayMigrate && ./gradlew bootRun"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
