version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: norutin-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    command: sh -c "./gradlew flywayMigrate && ./gradlew bootRun"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
